-  name: Do Config
   hosts: all
   gather_facts: false
   vars:
      ansible_connection: winrm 
      ansible_winrm_transport: ntlm
      ansible_winrm_port: 5985
      ansible_winrm_server_cert_validation: ignore
   handlers:
    - name: Restart SSHD
      ansible.windows.win_service:
        name: sshd
        state: restarted

   tasks:
    - name: Config Open SSH
      ansible.windows.win_powershell:
        script: |
          Get-WindowsCapability -Name OpenSSH.Server* -Online | Add-WindowsCapability -Online
          Set-Service -Name sshd -StartupType Automatic -Status Running

          $firewallParams = @{
          Name        = 'sshd-Server-In-TCP'
          DisplayName = 'Inbound rule for OpenSSH Server (sshd) on TCP port 22'
          Action      = 'Allow'
          Direction   = 'Inbound'
          Enabled     = 'True'  # This is not a boolean but an enum
          Profile     = 'Any'
          Protocol    = 'TCP'
          LocalPort   = 22
          }
          New-NetFirewallRule @firewallParams

          $shellParams = @{
          Path         = 'HKLM:\SOFTWARE\OpenSSH'
          Name         = 'DefaultShell'
          Value        = 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
          PropertyType = 'String'
          Force        = $true
          }
          New-ItemProperty @shellParams

    - name: Add SSH key
      ansible.windows.win_file:
        path: "C:\\ProgramData\\ssh\\administrators_authorized_keys"
        state: touch
        attributes: ReadOnly=False, System=False, Hidden=False

    - name: Set content
      ansible.builtin.lineinfile:
        path: "C:\\ProgramData\\ssh\\administrators_authorized_keys"
        line: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE6SJcka7Pidg6bMwcTLVqej+PlbnTe7iv07L+dDbEMu silveradmin@AAP-Test-Drive'
        create: true
        insertafter: EOF
      register: key_add_result

    - name: Disable password authentication
      ansible.builtin.lineinfile:
        path: "C:\\ProgramData\\ssh\\sshd_config"
        regexp: "^(#?)(PasswordAuthentication\\s+)(yes|no)"
        line: "PasswordAuthentication no"
      notify: Restart SSHD
